version: '3'

services:
  pg-database:
    image: postgres:16-alpine
    ports:
      - 5442:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=toor
      - POSTGRES_DB=bun-end

  pg-tests:
    image: postgres:16-alpine
    ports:
      - 5452:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=toor
      - POSTGRES_DB=bun-end-tests
